-- Sample data for santiere table
INSERT INTO santiere (
    titlu, judet, adresa, valoare, domeniu, subdomeniu,
    descriere, solicitari, observatii, dimensiune, sector, stadiu,
    beneficiar_nume, beneficiar_persoana, beneficiar_contact, beneficiar_email,
    antreprenor_nume, antreprenor_persoana, antreprenor_contact, antreprenor_email,
    proiectant_nume, proiectant_persoana, proiectant_contact, proiectant_email
) VALUES
(
    'Modernizare pod peste raul Prut',
    'IASI',
    'DN28, km 145+200, Ungheni',
    '3.882.383,83 RON',
    'Infrastructura',
    'Rutier',
    'Proiect de modernizare si consolidare pod peste raul Prut pe DN28. Lucrarile includ: consolidare structura de rezistenta, refacere suprastructura, modernizare sistem de evacuare ape pluviale, aplicare strat de uzura.',
    'Bitum rutier BNR 50/70, Mixturi asfaltice BA16, Marcaje rutiere permanente, Parapet metalic siguranta',
    'Termen de executie: 18 luni. Necesita autorizare ISU si aviz de mediu.',
    'Mediu',
    'Public',
    'Amenajare',
    'Consiliul Judetean Iasi',
    'Ing. Maria Popescu',
    '0232-xxx-xxx',
    'contactcj@iasi.ro',
    'SC Construct Grup SRL',
    'Ing. Ion Vasilescu',
    '0740-xxx-xxx',
    'office@constructgrup.ro',
    'Proiect Design SRL',
    'Arh. Ana Ionescu',
    '0745-xxx-xxx',
    'contact@proiectdesign.ro'
),
(
    'Extindere Spital Judetean',
    'BUCURESTI',
    'Strada Vitan Barzesti nr. 14, Sector 4',
    '25.500.000,00 RON',
    'Cladiri',
    'Civile',
    'Constructie corp nou spital cu 3 etaje si demisol. Suprafata construita: 4.200 mp. Dotari: bloc operator, 80 paturi, laborator analize, sectie radiologie.',
    'Beton C25/30, Otel beton BST500, BCA 40cm, Tamplarie PVC, Instalatii sanitare, Instalatii electrice',
    'Termen de executie: 24 luni. Necesita aviz DSP si aviz ISU.',
    'Mare',
    'Public',
    'Executie',
    'Primaria Sectorului 4',
    'Ing. Gheorghe Marinescu',
    '021-xxx-xxxx',
    'contact@ps4.ro',
    'SC MegaBuild Construct SRL',
    'Ing. Constantin Dumitrescu',
    '0744-xxx-xxx',
    'office@megabuild.ro',
    'Arhitectura Moderna SRL',
    'Arh. Mihai Stanescu',
    '0742-xxx-xxx',
    'contact@arhmoderna.ro'
),
(
    'Reabilitare drum comunal',
    'CLUJ',
    'DC23, comuna Floresti, sat Tauti',
    '1.450.000,00 RON',
    'Infrastructura',
    'Rutier',
    'Reabilitare drum comunal DC23 pe o lungime de 5,2 km. Lucrarile includ: scarificare, compactare, strat de baza piatra sparta, strat de uzura mixtura asfal tica BA8.',
    'Piatra sparta 4-8mm, Mixtura asfaltica BA8, Emulsie bituminoasa, Material antiderapant',
    'Termen de executie: 6 luni. Necesita aviz de mediu.',
    'Mic',
    'Public',
    'Licitatie',
    'Primaria comunei Floresti',
    'Primar Bogdan Pivariu',
    '0264-xxx-xxx',
    'primaria@floresti.ro',
    NULL,
    NULL,
    NULL,
    NULL,
    'Drumuri si Poduri Consult SRL',
    'Ing. Adrian Moldovan',
    '0741-xxx-xxx',
    'office@dpconsult.ro'
),
(
    'Ansamblu rezidential 120 apartamente',
    'TIMISOARA',
    'Strada Torontalului nr. 45, Timisoara',
    '18.900.000,00 RON',
    'Cladiri',
    'Civile',
    'Ansamblu rezidential compus din 3 blocuri cu regim de inaltime P+4E. Total 120 apartamente (60 apt. 2 camere, 50 apt. 3 camere, 10 apt. 4 camere). Spatii comerciale la parter. Parcare subterana 100 locuri.',
    'Beton C30/37, Caramida, BCA, Tamplarie PVC, Hidroizolatii, Termoizolatii, Instalatii complete',
    'Termen de executie: 30 luni. Faza: Structura de rezistenta.',
    'Mare',
    'Privat',
    'Executie',
    'SC Invest Imobiliare SRL',
    'Director Andrei Popescu',
    '0256-xxx-xxx',
    'contact@investimob.ro',
    'SC Premium Construct SRL',
    'Ing. Mihai Ionescu',
    '0743-xxx-xxx',
    'office@premiumconstruct.ro',
    'Arhitecti Asociati SRL',
    'Arh. Elena Popescu',
    '0746-xxx-xxx',
    'birou@arhitecti.ro'
),
(
    'Modernizare reteua apa-canal',
    'BRASOV',
    'Strada Republicii, Rasnov',
    '4.200.000,00 RON',
    'Infrastructura',
    'Utilitati',
    'Modernizare retea de apa potabila si canalizare pe o lungime totala de 8,5 km in orasul Rasnov. Inlocuire conducte existente cu teava PEHD. Modernizare 15 camine de vizitare.',
    'Teava PEHD d110-315mm, Fitinguri PEHD, Robineti sferice, Capace camine fonta ductila, Nisip pentru umpluturi',
    'Termen de executie: 12 luni. Interventie pe DN73A. Necesita aviz de mediu.',
    'Mediu',
    'Public',
    'Licitatie',
    'Compania de Apa Brasov',
    'Director Tehnic Ioan Mihai',
    '0268-xxx-xxx',
    'contact@apabrasov.ro',
    NULL,
    NULL,
    NULL,
    NULL,
    'Instalatii si Utilitati SRL',
    'Ing. Petru Avram',
    '0748-xxx-xxx',
    'contact@instutil.ro'
),
(
    'Complex comercial si birouri',
    'CONSTANTA',
    'Bulevardul Tomis nr. 234, Constanta',
    '32.000.000,00 RON',
    'Cladiri',
    'Comerciale',
    'Complex comercial cu 4 niveluri (S+P+2E+Tehn). Suprafata construita: 12.000 mp. Destinatie: spatii comerciale (8.000 mp), birouri (3.500 mp), parcare subterana (150 locuri).',
    'Beton C35/45, Otel S355, Fațada cortina, Sisteme HVAC, Lift persoane si marfa, Instalatii detectie incendiu, Grupuri sanitare, Finisaje premium',
    'Termen de executie: 28 luni. Autorizatie ISU categoria A.',
    'Mare',
    'Privat',
    'Amenajare',
    'SC Mall Development SRL',
    'Manager Ion Mihai',
    '0241-xxx-xxx',
    'contact@malldev.ro',
    'SC Elite Construction SRL',
    'Ing. Vasile Marin',
    '0747-xxx-xxx',
    'office@elitecons.ro',
    'Modern Architecture & Design SRL',
    'Arh. Alexandra Dumitrescu',
    '0742-xxx-xxx',
    'office@mad.ro'
),
(
    'Hala industriala productie',
    'ARGES',
    'Zona Industriala Mioveni',
    '8.750.000,00 RON',
    'Cladiri',
    'Industriale',
    'Hala industriala structura metalica cu destinatie productie componente auto. Suprafata construita: 5.600 mp. Inaltime utila: 9m. Include birouri administrative, vestiare, grupuri sanitare.',
    'Structura metalica, Panouri sandwich, Beton industrial C25/30, Instalatii electrice industriale, Sisteme ventilatie, Pod rulant 10t',
    'Termen de executie: 14 luni. Racord energie electrica 1MW.',
    'Mare',
    'Privat',
    'Executie',
    'SC Auto Parts Industry SRL',
    'Director Emil Radu',
    '0248-xxx-xxx',
    'contact@autoparts.ro',
    'SC Metal Construct Industrial SRL',
    'Ing. Gheorghe Pavel',
    '0745-xxx-xxx',
    'office@metalconstr.ro',
    'Proiect Industrial SRL',
    'Ing. Mircea Stoica',
    '0743-xxx-xxx',
    'contact@proiectind.ro'
),
(
    'Reteaua electrica cartier nou',
    'SIBIU',
    'Cartier Turnisor, Sibiu',
    '2.300.000,00 RON',
    'Infrastructura',
    'Electrice',
    'Proiect de extindere retea electrica pentru alimentare cartier rezidential nou (450 locuinte). Lungime retea: 6,8 km. Include 8 posturi de transformare de 250 kVA si retea de joasa tensiune.',
    'Stalp beton 9-12m, Cablu ACSR, Transformator 250kVA, Cablu subteran CYAbY, Sigurante, Tablouri electrice',
    'Termen de executie: 10 luni. Aviz de racordare E-Distributie.',
    'Mediu',
    'Public',
    'Amenajare',
    'Primaria Municipiului Sibiu',
    'Sef Serviciu Tehnic Vasile Ionescu',
    '0269-xxx-xxx',
    'primarie@sibiu.ro',
    'SC Electric Network SRL',
    'Ing. Marius Cristea',
    '0744-xxx-xxx',
    'office@electricnet.ro',
    'Electro Proiect Design SRL',
    'Ing. Alexandru Pop',
    '0746-xxx-xxx',
    'contact@electroproi.ro'
);
